// eda/manufacturing/excellon_writer.cpp
//
// P13 制造输出 · Excellon 钻孔写入器实现。

#include "eda/manufacturing/excellon_writer.h"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "eda/geometry/units.h"   // nm_to_mm
#include "eda/pcb/board.h"
#include "eda/pcb/via.h"

namespace eda::mfg {

namespace {

int64_t round_to_int64(double v) {
    return static_cast<int64_t>(std::round(v));
}

// 把 double 按指定小数位格式化（用于刀具直径展示，如 "0.30"）。
std::string fmt_fixed(double v, int decimals) {
    char buf[64];
    std::snprintf(buf, sizeof(buf), "%.*f", decimals, v);
    return std::string(buf);
}

}  // namespace

// ============================================================================
// ExcellonWriter
// ============================================================================

ExcellonWriter::ExcellonWriter() = default;
ExcellonWriter::~ExcellonWriter() = default;

void ExcellonWriter::set_precision(int integer_digits, int decimal_digits) {
    integer_digits_ = integer_digits;
    decimal_digits_ = decimal_digits;
}

int64_t ExcellonWriter::scale_factor() const {
    int64_t s = 1;
    for (int i = 0; i < decimal_digits_; ++i) s *= 10;
    return s;
}

std::string ExcellonWriter::format_coord(double mm) const {
    const int64_t scaled = round_to_int64(mm * static_cast<double>(scale_factor()));
    return std::to_string(scaled);
}

// ----------------------------------------------------------------------------
// 内部辅助：刀具分组（按 drill_diameter 去重，T1..Tn）。
// ----------------------------------------------------------------------------

namespace {

struct Hit {
    geometry::Point pos;
    int tool_index;  // 0-based → 输出 T{index+1}
};

// 收集钻孔位置并按直径分组，返回 (刀具表[直径, T编号], 命中列表)。
// 工具编号按"首次出现顺序"分配（保证可重现）。
struct ToolTable {
    // 直径(mm) → T编号(1-based)
    std::map<double, int> diameter_to_t;
    std::vector<double> ordered_diameters;  // index 0 → T1
};

// 把钻孔（已收集的 Hit）按刀具分组输出到 out 流，并在表头声明刀具。
void emit_body(std::ostringstream& out,
               const ToolTable& tools,
               const std::vector<Hit>& hits,
               const ExcellonWriter& writer,
               int integer_digits,
               int decimal_digits) {
    // 文件头（M48 ... %）
    out << "M48*\n";                                   // 头开始
    out << ";FORMAT=" << integer_digits << ":" << decimal_digits
        << " | METRIC | LZ*\n";   // 注释说明精度（仅给人读）
    out << "METRIC,LZ*\n";                              // mm，前导零省略
    // 刀具列表
    for (std::size_t i = 0; i < tools.ordered_diameters.size(); ++i) {
        const double dia = tools.ordered_diameters[i];
        const int t_num = static_cast<int>(i) + 1;
        out << "T" << t_num << "C" << fmt_fixed(dia, 2) << "*\n";
    }
    out << "%*\n";                                     // 头结束
    // 钻孔命令
    int current_t = -1;
    for (const auto& h : hits) {
        const int t_num = h.tool_index + 1;
        if (t_num != current_t) {
            out << "T" << (t_num < 10 ? "0" : "") << t_num << "*\n";  // T01/T02.. 选刀
            current_t = t_num;
        }
        out << "X" << writer.format_coord(geometry::nm_to_mm(h.pos.x))
            << "Y" << writer.format_coord(geometry::nm_to_mm(h.pos.y))
            << "*\n";
    }
    out << "T0*\n";     // 卸刀
    out << "M30*\n";    // 结束
}

}  // namespace

// ----------------------------------------------------------------------------
// write_pth —— plated（过孔）
// ----------------------------------------------------------------------------

std::string ExcellonWriter::write_pth(const pcb::Board& board) const {
    ToolTable tools;
    std::vector<Hit> hits;

    for (const auto& v : board.vias()) {
        if (!v) continue;
        const double dia = geometry::nm_to_mm(v->drill_diameter());
        // 查/插刀具（按首次出现顺序）
        int t_index;
        auto it = tools.diameter_to_t.find(dia);
        if (it != tools.diameter_to_t.end()) {
            t_index = it->second - 1;
        } else {
            t_index = static_cast<int>(tools.ordered_diameters.size());
            tools.ordered_diameters.push_back(dia);
            tools.diameter_to_t[dia] = t_index + 1;
        }
        hits.push_back({v->position(), t_index});
    }

    std::ostringstream out;
    out << ";Excellon PTH (plated) - generated by eda-engine P13*\n";
    // 即使没有孔也输出完整头尾，保证工厂上机能解析空文件
    emit_body(out, tools, hits, *this, integer_digits_, decimal_digits_);
    return out.str();
}

// ----------------------------------------------------------------------------
// write_npth —— non-plated（定位孔，骨架阶段空）
// ----------------------------------------------------------------------------

std::string ExcellonWriter::write_npth(const pcb::Board& board) const {
    (void)board;  // 当前数据模型无 NPTH 孔来源（待 Pad.drill 接入）
    ToolTable tools;
    std::vector<Hit> hits;
    std::ostringstream out;
    out << ";Excellon NPTH (non-plated) - generated by eda-engine P13*\n";
    emit_body(out, tools, hits, *this, integer_digits_, decimal_digits_);
    return out.str();
}

// ----------------------------------------------------------------------------
// write —— 一次两份
// ----------------------------------------------------------------------------

ExcellonOutput ExcellonWriter::write(const pcb::Board& board) const {
    return ExcellonOutput{
        write_pth(board),
        write_npth(board),
    };
}

}  // namespace eda::mfg
